<?xml version="1.0" encoding="utf-8"?><Database Name="Emplyees" Class="DataBaseConectionDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-OVEP8RV;Initial Catalog=Emplyees;Integrated Security=True" SettingsObjectName="FirstWpf.Properties.Settings" SettingsPropertyName="EmplyeesConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Emplyees" Member="Emplyees">
    <Type Name="Emplyee">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NChar(100) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>